### ISSUE TITLE
Labels for classification

### ISSUE THREAD

**Issue by anshudaur** [PrincetonLIPS/SketchGraphs#22]
Hello,

Thank you for sharing an interesting dataset. 
I am currently exploring this dataset as it consists of sketches. I  wanted to know how to get a unique label from the sequence information , so that could be used for either classification or object detection task? 
Also, what is the distribution of graphs sketches , are the graphs repeated in train-val and test sets?

Thank you 
Anshu

**Comment by wendazhou** [comment]
Hi Anshu,

due to the way the data is presented, there are no specific graph level labels that are suitable for graph level property prediction. In our paper, we did consider the supervised problem of predicting constraints from entities ("autoconstrain"), which can be viewed as a sequence to sequence supervised problem.

The current version of the data presents repeats between train-val-test due to natural repeats occurring in the data. I recommend you de-duplicate the data if you require unique data (happy to provide some example code if you need).

Hope that helps!
